[package]
workspace = ".."
name = "frontends"
version = "0.1.0"
authors = ["Justin Pombrio <justinpombrio@cs.brown.edu>"]
edition = "2018"

[dependencies]
rustbox = "*"
pretty = { path = "../pretty" }
