[package]
name = "synless"
version = "0.0.1"
authors = ["justinpombrio <zallambo@gmail.com>"]

[workspace]
members = [
  "forest",
  "pretty",
  "language",
  "frontends"]
default-members = [
  "forest",
  "pretty",
  "language",
  "frontends"]
