[package]
name = "synless"
version = "0.0.1"
authors = ["justinpombrio <zallambo@gmail.com>", "e-matteson <e.r.matteson@gmail.com>"]

[workspace]
members = [
  "utility",
  "forest",
  "pretty",
  "language",
  "frontends",
  "editor",
  "demo"]
default-members = [
  "utility",
  "forest",
  "pretty",
  "language",
  "frontends",
  "editor",
  "demo"]
