[package]
workspace = ".."
name = "pretty"
version = "0.1.0"
authors = ["Justin Pombrio <justinpombrio@cs.brown.edu>"]
edition = "2018"

[dependencies]
lazy_static = "*"
thiserror = "1.0"
typed-arena = "1.7"